[package]
authors = ["David Irvine <david.irvine@maidsafe.net>"]
name = "data_chain"
version = "0.1.0"

[dependencies]
itertools = "0.4.15"
maidsafe_utilities = "~0.5.4"
rayon = "~0.4.0"
rustc-serialize = "~0.3.19"
sodiumoxide = "~0.0.10"
xor_name = "0.1.0"

[dependencies.clippy]
optional = true
version = "~0.0.64"
