[package]
authors = ["David Irvine <david.irvine@maidsafe.net>"]
name = "data_blocks"
version = "0.1.0"

[dependencies]
maidsafe_utilities = "~0.5.4"
rustc-serialize = "~0.3.19"
sodiumoxide = "~0.0.10"

[dependencies.clippy]
optional = true
version = "~0.0.64"
