[package]
authors = ["David Irvine <david.irvine@maidsafe.net>"]
description = "Method of recording data securely on decentralised networks"
license = "GPL-3.0"
name = "data_chain"
readme = "README.md"
repository = "https://github.com/dirvine/data_chain"
version = "0.1.1"

[dependencies]
bit-vec = "~0.4.3"
fs2 = "0.2.5"
itertools = "0.4.15"
maidsafe_utilities = "~0.5.4"
rayon = "~0.4.0"
rustc-serialize = "~0.3.19"
sodiumoxide = "0.0.10"

[dependencies.clippy]
optional = true
version = "~0.0.64"

[dev-dependencies]
rand = "0.3.14"
tempdir = "0.3.4"
unwrap = "1.1.0"
